model:
  intermediate: True
  order: 2
  pruning:
    - 0
training_ds:
  is_tarred: false
  is_file: true
  data_dir: ???

validation_ds:
  is_tarred: false
  is_file: true
  data_dir: ???

vocab_file: ""
encryption_key: "tlt_encode"
